lang: "fr_FR"
dict_path: "./src/ipa-dict"
symbols:
  fr_FR:
    - ["s", "z"] # 0
    - ["t", "d"] # 1
    - ["n", "nj", "ɲ"] # 2
    - ["m"] # 3
    - ["ʁ"] # 4
    - ["l", "j"] # 5
    - ["ʃ", "ʒ"] # 6
    - ["k", "g"] # 7
    - ["f", "v"] # 8
    - ["p", "b"] # 9
  en_US:
    - ["s", "z"] # 0
    - ["t", "d", "θ", "ð"] # 1
    - ["n"] # 2
    - ["m"] # 3
    - ["r"] # 4
    - ["l"] # 5
    - ["tʃ", "dʒ", "ʃ", "ʒ"] # 6
    - ["k", "g"] # 7
    - ["f", "v"] # 8
    - ["p", "b"] # 9
  en_UK:
    - ["s", "z"] # 0
    - ["t", "d", "θ", "ð"] # 1
    - ["n"] # 2
    - ["m"] # 3
    - ["r"] # 4
    - ["l"] # 5
    - ["tʃ", "dʒ", "ʃ", "ʒ"] # 6
    - ["k", "g"] # 7
    - ["f", "v"] # 8
    - ["p", "b"] # 9